language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cM5fFP+l+P6qyjcuJixYUvmYdbqGR1h8PeFmsCsEedWphG1k311Ur0rqCN9qSWNXH88Grc4wTpp+35z5CjqINTmuTFunjYII/CHnNdtBhF3o8EsIY4Qf2Kw2Rslm2BjlhinMjLLY8Zc0AVim2KB9BhzLrKeOTS2hYm+yRHe76/k=
  file:
    - 'n-gram.js'
    - 'n-gram.min.js'
  on:
    tags: true
